blockRoutev5:
    path: wihtmlblockv5/block
    methods: [GET]
    defaults:
      _controller: 'Wihtmlblockv5\Controller\AdminWihtmlblockv5Controller::renderForm'

uploadRoutev5:
    path: wihtmlblockv5/block/upload
    methods: [GET, POST]
    defaults:
      _controller: 'Wihtmlblockv5\Controller\AdminWihtmlblockv5Controller::uploadForm'

addRoutev5:
    path: wihtmlblockv5/block/add
    methods: [GET, POST]
    defaults:
      _controller: 'Wihtmlblockv5\Controller\AdminWihtmlblockv5Controller::addBlock'

editRoutev5:
    path: wihtmlblockv5/block/edit
    methods: [GET, POST]
    defaults:
      _controller: 'Wihtmlblockv5\Controller\AdminWihtmlblockv5Controller::editBlock'

indexRoutev5:
    path: wihtmlblockv5/block/index
    methods: [GET, POST]
    defaults:
      _controller: 'Wihtmlblockv5\Controller\AdminWihtmlblockv5Controller::indexBlock'

hookRoute:
    path: wihtmlblockv5/block/hook
    methods: [GET, POST]
    defaults:
      _controller: 'Wihtmlblockv5\Controller\AdminWihtmlblockv5Controller::hookBlock'

